import type { ItemOutput, PageOutput } from './builder';

export interface PsjToTextOptions {
    /**
     * Additional MDX component imports.
     */
    imports?: { names: string[]; from: string }[];

    /**
     * Customize frontmatter fields.
     */
    frontmatter?: (title: string, description: string | undefined) => Record<string, unknown>;

    /**
     * Add a generated-file comment to the top.
     * @defaultValue true
     */
    addGeneratedComment?: boolean | string;

    /**
     * Include description in document body.
     * @defaultValue false
     */
    includeDescription?: boolean;
}

function buildFrontmatter(title: string, description: string | undefined, options: PsjToTextOptions): string {
    const base = options.frontmatter ? options.frontmatter(title, description) : { title, description, full: true };

    const lines = ['---'];
    for (const [key, value] of Object.entries(base)) {
        if (value === undefined) continue;
        if (typeof value === 'string') {
            lines.push(`${key}: ${JSON.stringify(value)}`);
        } else if (typeof value === 'boolean') {
            lines.push(`${key}: ${value}`);
        } else {
            lines.push(`${key}: ${JSON.stringify(value)}`);
        }
    }
    lines.push('---');
    return lines.join('\n');
}

function buildImports(options: PsjToTextOptions): string {
    const lines: string[] = [];
    // Always import the PSJAPIItem component
    lines.push(`import { PSJAPIItem } from '@psj/api/ui';`);
    if (options.imports) {
        for (const imp of options.imports) {
            lines.push(`import { ${imp.names.join(', ')} } from '${imp.from}';`);
        }
    }
    return lines.join('\n');
}

function generatedComment(options: PsjToTextOptions): string {
    const { addGeneratedComment = true } = options;
    if (!addGeneratedComment) return '';
    if (typeof addGeneratedComment === 'string') return `{/* ${addGeneratedComment} */}\n`;
    return `{/* This file was automatically generated by @psj/api — do not edit manually. */}\n`;
}

export function toText(entry: ItemOutput | PageOutput, options: PsjToTextOptions = {}): string {
    const parts: string[] = [];

    parts.push(buildFrontmatter(entry.info.title, entry.info.description, options));
    parts.push('');
    parts.push(generatedComment(options));
    parts.push(buildImports(options));
    parts.push('');

    if (options.includeDescription && entry.info.description) {
        parts.push(entry.info.description);
        parts.push('');
    }

    if (entry.type === 'item') {
        parts.push(
            `<PSJAPIItem schemaId={${JSON.stringify(entry.schemaId)}} itemKey={${JSON.stringify(entry.item.key)}} />`,
        );
    } else if (entry.type === 'page') {
        for (const item of entry.items) {
            parts.push(
                `<PSJAPIItem schemaId={${JSON.stringify(entry.schemaId)}} itemKey={${JSON.stringify(item.key)}} />`,
            );
        }
    }

    parts.push('');
    return parts.join('\n');
}

export function generateDocument(
    info: { title: string; description?: string },
    body: string,
    options: PsjToTextOptions = {},
): string {
    const parts: string[] = [];
    parts.push(buildFrontmatter(info.title, info.description, options));
    parts.push('');
    parts.push(generatedComment(options));
    parts.push(buildImports(options));
    parts.push('');
    parts.push(body);
    parts.push('');
    return parts.join('\n');
}
