from jupiterutils.PSJ_Interpreter import RUN_FILE, RUN_DEBUG, RUN_CODE
import win32gui

########################################################################
# PSJ Utilities
########################################################################

def JPT_RUN_LINE(message):
    return RUN_DEBUG(message, False)

def JPT_RUN_FILE(message):
    RUN_FILE(message, False)

def JPT_RUN_CODE(message):
    RUN_CODE(message, False)

class AssociateType:
    values = "JPT.AssociateType.values"
    AS_BARBODY = 0
    AS_BODY = 1
    AS_FACE = 2
    AS_EDGE = 3
    AS_ELEM = 4
    AS_ELEM1D = 5
    AS_SOLIDELEM = 6
    AS_NODE = 7
    AS_CONNECTION = 8
    AS_MASS = 9
    AS_CONTACT = 10
    AS_GROUP = 11

class BoolType:
    values = "JPT.BoolType.values"
    TRUE_VAL = 1
    FALSE_VAL = 0

class DItemType:
    values = "JPT.DItemType.values"
    UNKNOWN = 0
    PROJECT = 1
    INST = 2
    BODY = 3
    VERTEX = 4
    EDGE = 5
    FACE = 6
    SOLID = 7
    SHAPELINK = 8
    BODYLINK = 9
    NODE = 10
    ELEM = 11
    REF_BODY = 12
    REF_VERTEX = 13
    REF_EDGE = 14
    REF_FACE = 15
    REF_SOLID = 16
    REF_SHAPELINK = 17
    REF_BODYLINK = 18
    REF_NODE = 19
    REF_ELEM = 20
    LOCAL_SETTING = 21
    MATERIAL = 22
    ENTITY_ATTR_CAD_INFO = 23
    FEM_FIELD_SCALAR = 24
    FEM_FIELD_VECTOR = 25
    FEM_FIELD_TENSOR = 26
    COORD = 27
    LOADCASE = 28
    LBC_FORCE = 29
    LBC_FORCE_ND = 30
    LBC_FORCE_QUADRATIC = 31
    LBC_FORCE_SINE = 32
    LBC_FORCE_VECTOR = 33
    LBC_NOLIN1 = 34
    LBC_NOLIN3 = 35
    LBC_NOLIN4 = 36
    LBC_CONSTRAINT = 37
    LBC_ENFORCED_DISP = 38
    LBC_GRAVITY = 39
    LBC_G_PRESSURE = 40
    LBC_H_PRESSURE = 41
    LBC_T_PRESSURE = 42
    LBC_PRESSURE_QUADRATIC = 43
    LBC_PRESSURE_SINE = 44
    LBC_T_CENTRIFUGAL_FORCE = 45
    LBC_CS_CENTRIFUGAL_FORCE = 46
    LBC_TEMP_INI = 47
    LBC_TEMP_LOAD = 48
    LBC_TEMP_LOAD_GENERAL = 49
    LBC_TEMP_LOAD_ADVC_FILE = 50
    LBC_TEMP_LOAD_NASTRAN = 51
    LBC_TEMP_LOAD_ADVC_RESULT_REFERENCE = 52
    LBC_TEMP_BOUNDARY = 53
    LBC_CONCENTRATE_FLUX = 54
    LBC_SURFACE_FLUX = 55
    LBC_THERMAL_CONVECTION = 56
    LBC_ENFORCED_VELOCITY = 57
    LBC_ENFORCED_ACCELERATION = 58
    LBC_DYNAMIC_INITIAL_CONDITION = 59
    LBC_CONTACT_CLEARANCE = 60
    LBC_MAPPING_PRESSURE = 61
    LBC_MAPPING_FORCE = 62
    LBC_MAPPING_TEMP_LOAD = 63
    LBC_MAPPING_TEMP_INIT = 174
    LBC_MAPPING_TEMP_BOUNDARY = 64
    LBC_MAPPING_THERMAL_CONVECTION = 65
    LBC_INITSTRESS_GENERAL = 66
    LBC_INITSTRESS_MAPPING = 67
    LBC_PRETENSION = 68
    LBC_PRETENSION_ABAQUS = 69
    LBC_SURFACE_LOADS = 70
    LBC_SUBMODEL_FORCED_DISP = 71
    LBC_SUBMODEL_FORCED_TEMP = 72
    LBC_SUBMODEL_FORCED_FLUX = 73
    LBC_INSIDE_HEAT_GENERATION = 74
    LBC_RIGIDWALL = 75
    LBC_INIT_ANGULAR_VEL_ABAQUS = 76
    LBC_WELD = 77
    SUP_GROUP = 78
    GROUP = 79
    ELEMEDGE_GROUP = 80
    FIELD_DATA = 81
    PROPERTY_0D_MASS = 82
    PROPERTY_1D_BAR = 83
    PROPERTY_1D_BEAM = 84
    PROPERTY_1D_ROD = 85
    PROPERTY_1D_PLOT = 86
    PROPERTY_2D_SHELL = 87
    PROPERTY_2D_COMPOSITE_SHELL = 88
    PROPERTY_3D_SOLID = 89
    PROPERTY_3D_GASKET = 90
    PROPERTY_3D_COHESIVE = 91
    PROPERTY_3D_WELDBEAD = 92
    SECTION_GENERAL = 93
    SECTION_LIBRARY = 94
    SECTION_SKETCHER = 95
    CONNECT_MPC = 96
    CONNECT_SPRING = 97
    CONNECT_RBE2 = 98
    CONNECT_CONM = 99
    CONNECT_PROD = 100
    CONNECT_RBAR = 101
    CONNECT_RBE3 = 102
    CONNECT_BUSH = 103
    CONNECT_MOMENT = 104
    CONNECT_WELD = 105
    CONNECT_DAMPER = 106
    CONNECT_CONNECTOR = 107
    CONTACT_ADVC = 108
    CONTACT_NXNASTRAN = 109
    CONTACT_MSCNASTRAN = 110
    CONTACT_ABAQUS = 111
    CONTACT_ANSYS = 112
    CONTACT = 113
    CUSTOM_ATTR_STRING = 114
    CUSTOM_ATTR_VECTOR = 115
    CUSTOM_ATTR_DOUBLE = 116
    DCS = 117
    ADVCPROCESS = 118
    ADVCPROCESS_STATIC = 119
    ADVCPROCESS_DYNAMIC = 120
    ADVCPROCESS_EIGEN = 121
    ADVCPROCESS_CREEP = 122
    ADVCPROCESS_DYNAMIC_EXPLICIT = 123
    ADVCPROCESS_FATIGUE = 124
    ADVCPROCESS_MODAL_FREQ_RESP = 125
    ADVCPROCESS_RESP_SPEC = 126
    ADVCPROCESS_RAND_RESP = 127
    ADVCPROCESS_SSH = 128
    ADVCPROCESS_TH = 129
    ADVCJOB = 130
    ABAQSTEPS = 131
    ABAQSTEPS_STRUCT = 132
    ABAQSTEPS_THERMAL = 133
    ABAQSTEPS_STRUCT_STATIC = 134
    ABAQSTEPS_STRUCT_FREQUENCY = 135
    ABAQSTEPS_STRUCT_COUPLEDTD = 136
    ABAQSTEPS_STRUCT_DYNAMIC = 137
    ABAQSTEPS_STRUCT_DYNAMIC_COUPLEDTD = 138
    ABAQSTEPS_STRUCT_DYNAMIC_EXPLICIT = 139
    ABAQSTEPS_STRUCT_STATICRISK = 140
    ABAQSTEPS_THERMAL_SS = 141
    ABAQSTEPS_THERMAL_TRANSIENT = 142
    ABAQUSJOB = 143
    LBC_MAPPING_HEATFLUX = 144
    CONNECT_GAP = 145
    ANSYSJOB = 146
    NASTRANJOB = 147
    DYANAMISJOB = 148
    WELDORDER = 149
    ATTRIBUTE_FXWELD = 150
    ACTRANJOB = 151
    LSDYNAJOB = 152
    NCS = 153
    ATTRIBUTE_PS_BLENDSURFACE = 154
    LBC_DOFSET = 155
    BEAM_PROP_ATTR = 156
    BEAM_PROP_ATTR2 = 157
    SHELL_PROP_ATTR = 158
    CONN_PROP_ATTR = 159
    LBC_PRETENSION_NXN = 160
    LBC_MAPPING_TEMP_MARINE_ENGINE = 161
    USER_PROP = 162
    CONNECTION_ELEMENT = 163
    CONTACT_TSSS = 164
    LBC_MAPPING_FORCEDDISPLACEMENT = 165
    LBC_MAPPING_FORCED_TEMP = 166
    NASTRAN_POSTJOB = 167
    ADVC2_POSTJOB = 168
    USER_RESULT = 169
    LBC_PRETENSION_ADVC = 170
    CONTACT_TSSOLVER = 171
    NASTRAN_HDF5_POSTJOB = 172
    PROPERTY_2D_RIGID_BODY = 175
    LBC_PRETENSION_SUNSHINE = 176
    CONTACT_PERMAS = 179
    FRONTISTRSTEP = 181
    UNV_POSTJOB = 182
    TSV_POSTJOB = 183
    MARCJOB = 184
    MARCSTEPS_STRUCT_STATIC = 185
    MARCSTEPS_STRUCT_FREQUENCY = 186
    MARCSTEPS_THERMAL_SS = 187
    MARCSTEPS_THERMAL_TRANSIENT = 188
    PERIDYNAMIC_MODEL = 189
    PD_BODY_FORCE = 190
    PERIDYNAMIC_FRACTURE_MODEL = 191
    POST_RESULT_CURVE = 194
    POST_FREQ_ANALYSIS = 195
    POST_FREQ_RESULT_CURVE = 196
    POST_FREQ_LOAD = 197
    POST_FREQ_LOADCASE = 198
    POST_FREQ_RESPONSE = 199
    POST_FREQ_INTERACTIVE_LOAD_AND_RESPONSE = 200
    POST_FREQ_RESULT_MPF_CURVE = 201
    POST_TRANS_ANALYSIS = 202
    POST_TRANS_RESULT_CURVE = 203
    POST_TRANS_LOAD = 204
    POST_TRANS_LOADCASE = 205
    POST_TRANS_RESPONSE = 206
    POST_TRANS_RESULT_MPF_CURVE = 207
    POST_BTXBTA = 208
    POST_ACTRAN_ANALYSIS = 209
    POST_ACTRAN_DOMAIN_GROUP = 210
    POST_ACTRAN_DOMAIN = 211
    POST_ACTRAN_SURFACE_GROUP = 212
    POST_ACTRAN_SURFACE = 213
    POST_ACTRAN_POINT_GROUP = 214
    POST_ACTRAN_POINT = 215
    POST_ACTRAN_LOADCASE = 216
    CUSTOM_TAS_RAO = 217
    POST_GURURI_RESPONSE = 218
    POST_GURURI_SWEEP = 219
    POST_FFT_CONDITION = 220
    POST_FREQ_ANALYSIS_SOLVER = 221
    POST_FREQ_LOAD_SOLVER = 222
    POST_FREQ_RESPONSE_SOLVER = 223
    POST_FREQ_INTERACTIVE_ANALYSIS = 224
    POST_MBD_FATIGUE_ANALYSIS = 225
    POST_MBD_FATIGUE_RESULT = 226
    POST_MBD_FATIGUE_THERMAL_STRESS = 227
    POST_MBD_FATIGUE_NODAL_TEMPERATURE = 228
    POST_MBD_FATIGUE_PROPERTY = 229
    POST_MBD_FATIGUE_CONDITION = 230
    CONNECT_LINEARGAP = 231
    POST_MBD_FATIGUE_STRESS_RECOVERY = 233
    POST_ACTRAN_CONTRIBUTION_RESULT_CURVE = 235
    POST_MAC_SENSOR = 236
    POST_MAC_SENSOR_COLLECTION = 237
    POST_SURFACE_DISTANCE = 238
    CUSTOM_SESSION = 239
    POST_ACOUSTIC_TRANSMISSION_LOSS = 240
    POST_ACOUSTIC_TL_PCH_RESULT = 241
    POST_ACOUSTIC_TL_CONDITION = 242
    POST_ACOUSTIC_TRANSMISSION_LOSS_CONDITION_CURVE = 243
    CUSTOM_SESSION_NAGISA = 244
    PD_JOB = 245
    WAON_ANALYSIS_JOB = 246
    POST_MAC_DATA = 247
    POST_ROUGH_SURF = 248
    POST_MAC_FACTOR_CALCULATION = 249
    PD_CURVE = 251
    PD_PERIDYNAMIC_MATERIAL = 252
    PD_FRACTURE_MODEL = 253
    PD_PART = 254
    PD_BOUNDARY_CONDITION = 255
    PD_LOAD_CONDITION = 256
    PD_SOLVER = 257
    PD_EXPORT_SETTING = 258
    CONTACT_LSDYNA = 259
    ADVCPROCESS_RDNLK = 260
    WAON_STRUCTURE_MANAGER = 261
    WAON_SOUNDSOURCE_MANAGER = 262
    WAON_ABSORPTION_MANAGER = 263
    POST_FATIGUE_MATERIAL = 264
    WAON_FIELDCAL_MANAGER = 265
    WAON_TRANSFERFUNC_MANAGER = 266
    POST_RESULT_TREE_RENAME = 267
    PD_CONTACT_MODEL = 268
    PD_CRACK_MODEL = 269
    POST_TRANS_ANALYSIS_SOLVER = 272
    POST_TRANS_LOAD_SOLVER = 273
    POST_TRANS_RESPONSE_SOLVER = 274
    LBC_ACCELERATION_LOAD_ACCEL = 275
    LBC_ACCELERATION_LOAD_ACCEL1 = 276
    LBC_ENFORCED_RELATIVE_DISP = 277
    LBC_MUFFLER_T_CONVECTION = 280
    LBC_MUFFLER_T_TEMP_LOAD = 281
    POST_RESULT_TREE_DELETED = 282
    LBC_PRETENSION_MSC_NASTRAN = 283
    LBC_PRESCRIBED_MOTION = 284
    DAMPING_PART_STIFFNESS = 285
    CONNECT_RBC = 286
    POST_ERP = 287
    POST_PLOT_ERP = 288
    LBC_COIL = 289
    LBC_THERMAL_SHELL_CONVECTION = 290
    LBC_EXTERNAL_CURRENT_DENSITY = 291
    LBC_MAGNETIC_POTENTIAL = 292
    LBC_SURFACE_CURRENT_DENSITY = 293
    LBC_ELECTRIC_POTENTIAL = 294
    PERMASJOB = 173
    LBC_RADIATION = 177
    LBC_THERMAL_ATTRIBUTES = 178
    FRONTISTRJOB = 180
    OPTISHAPE_TS_JOB = 232
    CONTACT_FRONTISTR = 234
    POST_NODE = 192
    POST_ELEM = 193
    VIRTUAL_FLUID_MASS = 250
    CUSTOM_NOTE = 270
    CUSTOM_NOTE_COLLECTION = 271
    MEASURE_NOTE = 278
    MEASURE_NOTE_COLLECTION = 279
    END = 295

class DTableType:
    values = "JPT.DTableType.values"
    DTABLE_UNKNOWN = 0
    DTABLE_BODY = 5
    DTABLE_SHAPE = 3
    DTABLE_NODE = 7
    DTABLE_ELEM = 8
    DTABLE_LOCAL_SETTING = 15
    DTABLE_MATERIAL = 16
    DTABLE_COORDINATE = 18
    DTABLE_LOADCASE = 19
    DTABLE_LBC_START = 20
    DTABLE_LBC_END = 55
    DTABLE_FIELD_DATA = 56
    DTABLE_GROUP = 59
    DTABLE_PROPERTY = 61
    DTABLE_CONNECTION = 63
    DTABLE_CONTACT = 64
    DTABLE_ADVCPROCESS = 67
    DTABLE_ADVCJOB = 68
    DTABLE_ABAQSTEPS = 69
    DTABLE_ABAQUSJOB = 70
    DTABLE_ANSYSJOB = 71
    DTABLE_NASTRANJOB = 72
    DTABLE_DYNAMISJOB = 73
    DTABLE_ACTRANJOB = 75
    DTABLE_LSDYNAJOB = 76
    DTABLE_SUP_GROUP = 58
    DTABLE_ELEMEDGE_GROUP = 60
    DTABLE_SECTION = 62
    DTABLE_CUSTOM_ATTRIBUTE = 65
    DTABLE_USER_PROPERTY = 84
    DTABLE_POSTJOB = 86
    DTABLE_USER_RESULT = 87
    DTABLE_LBC_DOFSET = 79
    DTABLE_POST_NODE = 96
    DTABLE_POST_ELEM = 97
    DTABLE_POST_SURFACE_DISTANCE = 130
    DTABLE_CUSTOM_NOTE = 154
    DTABLE_CUSTOM_NOTE_COLLECTION = 155
    DTABLE_MEASURE_NOTE = 160
    DTABLE_MEASURE_NOTE_COLLECTION = 161

class ElemKind:
    values = "JPT.ElemKind.values"
    ELEMKIND_UNKNOWN = 0
    ELEMKIND_0D = 1
    ELEMKIND_1D = 2
    ELEMKIND_2D = 3
    ELEMKIND_3D = 4
    ELEMKIND_SP = 5

class ElemType:
    values = "JPT.ElemType.values"
    ELEMTYPE_UNKNOWN = 0
    ELEMTYPE_POINT = 1
    ELEMTYPE_LINE2 = 2
    ELEMTYPE_LINE3 = 3
    ELEMTYPE_TRI3 = 4
    ELEMTYPE_TRI6 = 5
    ELEMTYPE_QUAD4 = 6
    ELEMTYPE_QUAD8 = 7
    ELEMTYPE_TET4 = 8
    ELEMTYPE_TET10 = 9
    ELEMTYPE_HEX8 = 10
    ELEMTYPE_HEX20 = 11
    ELEMTYPE_PRISM6 = 12
    ELEMTYPE_PRISM15 = 13
    ELEMTYPE_PYRAMID5 = 14
    ELEMTYPE_PYRAMID13 = 15
    ELEMTYPE_PLOT = 16
    ELEMTYPE_QUAD6 = 17
    ELEMTYPE_QUAD9 = 18
    ELEMTYPE_PRISM12 = 19
    ELEMTYPE_HEX18 = 20
    ELEMTYPE_RBE = 21
    ELEMTYPE_MASS = 22
    ELEMTYPE_VIRTUAL = 23

class EntityType:
    values = "JPT.EntityType.values"
    UNKNOWN = 0
    PROJECT = 1
    INST = 2
    BODY = 3
    VERTEX = 4
    EDGE = 5
    FACE = 6
    SOLID = 7
    SHAPELINK = 8
    BODYLINK = 9
    NODE = 10
    ELEM = 11
    REF_BODY = 12
    REF_VERTEX = 13
    REF_EDGE = 14
    REF_FACE = 15
    REF_SOLID = 16
    REF_SHAPELINK = 17
    REF_BODYLINK = 18
    REF_NODE = 19
    REF_ELEM = 20
    LOCAL_SETTING = 21
    MATERIAL = 22
    ENTITY_ATTR_CAD_INFO = 23
    FEM_FIELD_SCALAR = 24
    FEM_FIELD_VECTOR = 25
    FEM_FIELD_TENSOR = 26
    COORD = 27
    LOADCASE = 28
    LBC_FORCE = 29
    LBC_FORCE_ND = 30
    LBC_FORCE_QUADRATIC = 31
    LBC_FORCE_SINE = 32
    LBC_FORCE_VECTOR = 33
    LBC_NOLIN1 = 34
    LBC_NOLIN3 = 35
    LBC_NOLIN4 = 36
    LBC_CONSTRAINT = 37
    LBC_ENFORCED_DISP = 38
    LBC_GRAVITY = 39
    LBC_G_PRESSURE = 40
    LBC_H_PRESSURE = 41
    LBC_T_PRESSURE = 42
    LBC_PRESSURE_QUADRATIC = 43
    LBC_PRESSURE_SINE = 44
    LBC_T_CENTRIFUGAL_FORCE = 45
    LBC_CS_CENTRIFUGAL_FORCE = 46
    LBC_TEMP_INI = 47
    LBC_TEMP_LOAD = 48
    LBC_TEMP_LOAD_GENERAL = 49
    LBC_TEMP_LOAD_ADVC_FILE = 50
    LBC_TEMP_LOAD_NASTRAN = 51
    LBC_TEMP_LOAD_ADVC_RESULT_REFERENCE = 52
    LBC_TEMP_BOUNDARY = 53
    LBC_CONCENTRATE_FLUX = 54
    LBC_SURFACE_FLUX = 55
    LBC_THERMAL_CONVECTION = 56
    LBC_ENFORCED_VELOCITY = 57
    LBC_ENFORCED_ACCELERATION = 58
    LBC_DYNAMIC_INITIAL_CONDITION = 59
    LBC_CONTACT_CLEARANCE = 60
    LBC_MAPPING_PRESSURE = 61
    LBC_MAPPING_FORCE = 62
    LBC_MAPPING_TEMP_LOAD = 63
    LBC_MAPPING_TEMP_INIT = 174
    LBC_MAPPING_TEMP_BOUNDARY = 64
    LBC_MAPPING_THERMAL_CONVECTION = 65
    LBC_INITSTRESS_GENERAL = 66
    LBC_INITSTRESS_MAPPING = 67
    LBC_PRETENSION = 68
    LBC_PRETENSION_ABAQUS = 69
    LBC_SURFACE_LOADS = 70
    LBC_SUBMODEL_FORCED_DISP = 71
    LBC_SUBMODEL_FORCED_TEMP = 72
    LBC_SUBMODEL_FORCED_FLUX = 73
    LBC_INSIDE_HEAT_GENERATION = 74
    LBC_RIGIDWALL = 75
    LBC_INIT_ANGULAR_VEL_ABAQUS = 76
    LBC_WELD = 77
    SUP_GROUP = 78
    GROUP = 79
    ELEMEDGE_GROUP = 80
    FIELD_DATA = 81
    PROPERTY_0D_MASS = 82
    PROPERTY_1D_BAR = 83
    PROPERTY_1D_BEAM = 84
    PROPERTY_1D_ROD = 85
    PROPERTY_1D_PLOT = 86
    PROPERTY_2D_SHELL = 87
    PROPERTY_2D_COMPOSITE_SHELL = 88
    PROPERTY_3D_SOLID = 89
    PROPERTY_3D_GASKET = 90
    PROPERTY_3D_COHESIVE = 91
    PROPERTY_3D_WELDBEAD = 92
    SECTION_GENERAL = 93
    SECTION_LIBRARY = 94
    SECTION_SKETCHER = 95
    CONNECT_MPC = 96
    CONNECT_SPRING = 97
    CONNECT_RBE2 = 98
    CONNECT_CONM = 99
    CONNECT_PROD = 100
    CONNECT_RBAR = 101
    CONNECT_RBE3 = 102
    CONNECT_BUSH = 103
    CONNECT_MOMENT = 104
    CONNECT_WELD = 105
    CONNECT_DAMPER = 106
    CONNECT_CONNECTOR = 107
    CONTACT_ADVC = 108
    CONTACT_NXNASTRAN = 109
    CONTACT_MSCNASTRAN = 110
    CONTACT_ABAQUS = 111
    CONTACT_ANSYS = 112
    CONTACT = 113
    CUSTOM_ATTR_STRING = 114
    CUSTOM_ATTR_VECTOR = 115
    CUSTOM_ATTR_DOUBLE = 116
    DCS = 117
    ADVCPROCESS = 118
    ADVCPROCESS_STATIC = 119
    ADVCPROCESS_DYNAMIC = 120
    ADVCPROCESS_EIGEN = 121
    ADVCPROCESS_CREEP = 122
    ADVCPROCESS_DYNAMIC_EXPLICIT = 123
    ADVCPROCESS_FATIGUE = 124
    ADVCPROCESS_MODAL_FREQ_RESP = 125
    ADVCPROCESS_RESP_SPEC = 126
    ADVCPROCESS_RAND_RESP = 127
    ADVCPROCESS_SSH = 128
    ADVCPROCESS_TH = 129
    ADVCJOB = 130
    ABAQSTEPS = 131
    ABAQSTEPS_STRUCT = 132
    ABAQSTEPS_THERMAL = 133
    ABAQSTEPS_STRUCT_STATIC = 134
    ABAQSTEPS_STRUCT_FREQUENCY = 135
    ABAQSTEPS_STRUCT_COUPLEDTD = 136
    ABAQSTEPS_STRUCT_DYNAMIC = 137
    ABAQSTEPS_STRUCT_DYNAMIC_COUPLEDTD = 138
    ABAQSTEPS_STRUCT_DYNAMIC_EXPLICIT = 139
    ABAQSTEPS_STRUCT_STATICRISK = 140
    ABAQSTEPS_THERMAL_SS = 141
    ABAQSTEPS_THERMAL_TRANSIENT = 142
    ABAQUSJOB = 143
    LBC_MAPPING_HEATFLUX = 144
    CONNECT_GAP = 145
    ANSYSJOB = 146
    NASTRANJOB = 147
    DYANAMISJOB = 148
    WELDORDER = 149
    ATTRIBUTE_FXWELD = 150
    ACTRANJOB = 151
    LSDYNAJOB = 152
    NCS = 153
    ATTRIBUTE_PS_BLENDSURFACE = 154
    LBC_DOFSET = 155
    BEAM_PROP_ATTR = 156
    BEAM_PROP_ATTR2 = 157
    SHELL_PROP_ATTR = 158
    CONN_PROP_ATTR = 159
    LBC_PRETENSION_NXN = 160
    LBC_MAPPING_TEMP_MARINE_ENGINE = 161
    USER_PROP = 162
    CONNECTION_ELEMENT = 163
    CONTACT_TSSS = 164
    LBC_MAPPING_FORCEDDISPLACEMENT = 165
    LBC_MAPPING_FORCED_TEMP = 166
    NASTRAN_POSTJOB = 167
    ADVC2_POSTJOB = 168
    POST_NODE = 182
    POST_ELEM = 183
    END = 184

class MsgBoxType:
    values = "JPT.MsgBoxType.values"
    MB_WARNING_YESNOCANCEL = 0
    MB_WARNING_YESNO = 1
    MB_WARNING_OK = 2
    MB_WARNING_OKCANCEL = 3
    MB_INFORMATION_YESNOCANCEL = 4
    MB_INFORMATION_YESNO = 5
    MB_INFORMATION_OK = 6
    MB_INFORMATION_OKCANCEL = 7
    MB_CRITICAL_OK = 8

class PathType:
    values = "JPT.PathType.values"
    PROGRAM_PATH = 0
    TEMP_PATH = 1
    APPDATA_PATH = 2
    DOC_PATH = 3
    MATERIAL_LIB_FILE_PATH = 4
    MATERIAL_USER_FILE_PATH = 5
    DATABASE_PATH = 6
    SUNSHINE_PATH = 7
    IDE_DATA_PATH = 8
    FILE_PATH = 9
    PSJ_COMMAND_PATH = 10

class SelectMethodType:
    values = "JPT.SelectMethodType.values"
    SELMTD_NONE = 0
    SELMTD_BODY = 1
    SELMTD_BAR_BODY = 2
    SELMTD_FACE = 3
    SELMTD_EDGE = 4
    SELMTD_VERTEX = 5
    SELMTD_SOLIDELEM = 6
    SELMTD_ELEM = 7
    SELMTD_ELEM1D = 8
    SELMTD_ELEM_EDGE = 9
    SELMTD_NODE = 10
    SELMTD_CONDITION = 11
    SELMTD_COORDINATE = 12
    SELMTD_GROUP = 13
    SELMTD_PROPERTY = 14
    SELMTD_FACE_POINT = 15
    SELMTD_EDGE_POINT = 16
    SELMTD_VIEW_ITEM = 17
    SELMTD_CONDITION_MPC = 18
    SELMTD_CONDITION_RBE2 = 19
    SELMTD_CONDITION_RBE3 = 20
    SELMTD_CONDITION_RBAR = 21
    SELMTD_CONDITION_SPRING = 22
    SELMTD_CONDITION_MASS = 23
    SELMTD_CONDITION_CONNECTOR = 24
    SELMTD_CONDITION_PRESSURE = 25
    SELMTD_CONDITION_FORCE = 26
    SELMTD_CONDITION_ENFORCE = 27
    SELMTD_CONDITION_CONSTRAIN = 28
    SELMTD_CONDITION_TEMP = 29
    SELMTD_SOLID_TET4 = 30
    SELMTD_SOLID_TET10 = 31
    SELMTD_SOLID_HEX8 = 32
    SELMTD_SOLID_HEX20 = 33
    SELMTD_SOLID_PENT6 = 34
    SELMTD_SOLID_PEN15 = 35
    SELMTD_SOLID_PYRD5 = 36
    SELMTD_SOLID_PYR13 = 37
    SELMTD_SHELL_TRI3 = 38
    SELMTD_SHELL_TRI6 = 39
    SELMTD_SHELL_QUAD4 = 40
    SELMTD_SHELL_QUAD8 = 41

class UnitType:
    values = "JPT.UnitType.values"
    Unit_Length = 0
    Unit_Time = 1
    Unit_Mass = 2
    Unit_Force = 3
    Unit_Angle = 4
    Unit_Temperature = 5
    Unit_Area = 6
    Unit_Volume = 7
    Unit_Velocity = 8
    Unit_Acceleration = 9
    Unit_RotateVelo = 10
    Unit_RotateAcc = 11
    Unit_Moment = 12
    Unit_Pressure = 13
    Unit_Density = 14
    Unit_Stiffness = 15
    Unit_RotateStiff = 16
    Unit_DampingCoef = 17
    Unit_RotateDampingCoef = 18
    Unit_Modulus = 19
    Unit_Energy = 20
    Unit_Power = 21
    Unit_ThermalExCoef = 22
    Unit_ThermalConductivity = 23
    Unit_ConvectionCoef = 24
    Unit_SpecificHeat = 25
    Unit_HeatFlux = 26
    Unit_HeatGeneration = 27
    Unit_LinearDensity = 28
    Unit_SurfaceDensity = 29
    Unit_AreaMomentInertia = 30
    Unit_TorsionalConst = 31
    Unit_WarpCoef = 32
    Unit_LinearMassMomentIntertia = 33
    Unit_MomentInertia = 34
    Unit_Stress = 35
    Unit_Strain = 36
    Unit_StrainEnergy = 37
    Unit_ThermalEnergy = 38
    Unit_Frequency = 39
    Unit_VolumeEnergyDensity = 40
    Unit_ElectricalResistivity = 41
    Unit_StressReciprocal = 42
    Unit_ThermalRadiation = 43
    Unit_Displacement = 44
    Unit_EnergyDensity = 45
    Unit_TemperatureGradient = 46
    Unit_Current = 47
    Unit_Voltage = 48
    Unit_CurrentDensity = 49
    Unit_ElectricalConductivity = 50
    Unit_MagneticPotential = 51
    Unit_SurfaceCurrentDensity = 52

class JPT:
    AssociateType = AssociateType()
    BoolType = BoolType()
    DItemType = DItemType()
    DTableType = DTableType()
    ElemKind = ElemKind()
    ElemType = ElemType()
    EntityType = EntityType()
    MsgBoxType = MsgBoxType()
    PathType = PathType()
    SelectMethodType = SelectMethodType()
    UnitType = UnitType()

    def DItem():
        return "JPT.DItem()"

    def DFace():
        return "JPT.DFace()"

    def DBody():
        return "JPT.DBody()"

    def DEdge():
        return "JPT.DEdge()"

    def DElem():
        return "JPT.DElem()"

    def DGroup():
        return "JPT.DGroup()"

    def DNode():
        return "JPT.DNode()"

    def VersionInfo():
        return "JPT.VersionInfo()"

    def TVector3d():
        return "JPT.TVector3d()"

    def DItemVector():
        return "JPT.DItemVector()"

    def BodyVector():
        return "JPT.BodyVector()"

    def FaceVector():
        return "JPT.FaceVector()"

    def ElemVector():
        return "JPT.ElemVector()"

    def GroupVector():
        return "JPT.GroupVector()"

    def NodeVector():
        return "JPT.NodeVector()"

    def EdgeVector():
        return "JPT.EdgeVector()"

    def DItemPairVector():
        return "JPT.DItemPairVector()"

