#!/usr/bin/env bun
/**
 * Auto-discovers API versions from:
 *   1. `.gitmodules` at repo root → frozen versions (submodule, branch = release/<X.Y.Z>)
 *   2. `content/api/` scan         → latest version (not in .gitmodules, not __template__)
 *
 * Then regenerates:
 *   - lib/versions.ts
 *   - source.config.ts  (the workspaces block)
 *   - lib/source/index.tsx  (imports + apiSources map)
 *
 * Usage:
 *   bun scripts/sync-versions.ts           # write files
 *   bun scripts/sync-versions.ts --dry-run # preview only
 */

import { existsSync } from 'node:fs';
import { cp, readdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';

const DRY_RUN = process.argv.includes('--dry-run');
const docsRoot = process.cwd(); // run from apps/docs

// ── Paths ─────────────────────────────────────────────────────────────────────

const repoRoot = path.resolve(docsRoot, '../..');
const gitmodulesPath = path.join(repoRoot, '.gitmodules');
const contentApiDir = path.join(docsRoot, 'content/api');
const templateDir = path.join(contentApiDir, '__template__');
const versionsPath = path.join(docsRoot, 'lib/versions.ts');
const sourceConfigPath = path.join(docsRoot, 'source.config.ts');
const sourceIndexPath = path.join(docsRoot, 'lib/source/index.tsx');

// ── Step 1: Parse .gitmodules for frozen versions ─────────────────────────────

async function parseFrozenVersions(): Promise<string[]> {
    if (!existsSync(gitmodulesPath)) return [];
    const content = await readFile(gitmodulesPath, 'utf8');
    const frozen: string[] = [];
    // Match lines like: branch = release/5.1.0
    for (const match of content.matchAll(/branch\s*=\s*release\/(\d+\.\d+\.\d+)/g)) {
        frozen.push(match[1]);
    }
    return [...new Set(frozen)];
}

// ── Step 2: Scan content/api/ for the latest version ─────────────────────────

async function detectLatestVersion(frozen: Set<string>): Promise<string | null> {
    const entries = await readdir(contentApiDir, { withFileTypes: true });
    const candidates = entries
        .filter((e) => e.isDirectory() && !e.name.startsWith('__'))
        .map((e) => e.name)
        .filter((n) => !frozen.has(n));

    if (candidates.length === 0) return null;
    // Sort semver descending, pick highest
    return candidates.sort((a, b) => compareSemver(b, a))[0];
}

function compareSemver(a: string, b: string): number {
    const pa = a.split('.').map(Number);
    const pb = b.split('.').map(Number);
    for (let i = 0; i < 3; i++) {
        if ((pa[i] ?? 0) !== (pb[i] ?? 0)) return (pa[i] ?? 0) - (pb[i] ?? 0);
    }
    return 0;
}

// ── Step 3: Ensure each version has a source.config.ts ───────────────────────

async function ensureVersionConfig(version: string): Promise<void> {
    const versionDir = path.join(contentApiDir, version);
    const configDest = path.join(versionDir, 'source.config.ts');
    if (!existsSync(configDest)) {
        const templateConfig = path.join(templateDir, 'source.config.ts');
        if (existsSync(templateConfig)) {
            if (!DRY_RUN) await cp(templateConfig, configDest);
            console.log(`  + Created ${path.relative(docsRoot, configDest)}`);
        } else {
            console.warn(`  !! Template not found at ${templateConfig}; skipping`);
        }
    }
}

// ── Step 4: Generate lib/versions.ts ─────────────────────────────────────────

function generateVersionsTs(latest: string, frozen: string[]): string {
    const allVersions = [latest, ...frozen].sort((a, b) => compareSemver(b, a));
    const metaEntries = allVersions
        .map((v) => {
            const isFrozen = frozen.includes(v);
            return `    '${v}': { label: '${v}', frozen: ${isFrozen}, sourceType: '${isFrozen ? 'git' : 'local'}' },`;
        })
        .join('\n');
    const activeArray = allVersions.map((v) => `'${v}'`).join(', ');

    return `// !! AUTO-GENERATED by scripts/sync-versions.ts — do not edit manually.
export type VersionMeta = {
    label: string;
    frozen: boolean;
    sourceType: 'local' | 'git';
};

export const VERSION_META = {
${metaEntries}
} satisfies Record<string, VersionMeta>;

export type CanonicalVersion = keyof typeof VERSION_META;

export const ACTIVE_VERSIONS = [${activeArray}] as const;
export type ActiveVersion = (typeof ACTIVE_VERSIONS)[number];

// ─── Helpers ──────────────────────────────────────────────────────────────────

export function isVersionActive(key: string): boolean {
    return (ACTIVE_VERSIONS as readonly string[]).includes(key);
}

export function getVersionMeta(key: string): VersionMeta | null {
    return VERSION_META[key as CanonicalVersion] ?? null;
}
`;
}

// ── Step 5: Generate source.config.ts (workspaces block) ─────────────────────

async function updateSourceConfig(allVersions: string[]): Promise<void> {
    let content = await readFile(sourceConfigPath, 'utf8');

    // Build the workspaces object entries
    const workspaceEntries = allVersions
        .map(
            (v) =>
                `        '${v}': { dir: 'content/api/${v}', config: await import('./content/api/${v}/source.config.ts') },`,
        )
        .join('\n');

    const workspacesBlock = `    workspaces: {
${workspaceEntries}
    },`;

    // Replace between SYNC-START and SYNC-END markers, or inject before closing `})` of defineConfig
    const markerStart = '    // SYNC-VERSIONS:START';
    const markerEnd = '    // SYNC-VERSIONS:END';

    if (content.includes(markerStart)) {
        const start = content.indexOf(markerStart);
        const end = content.indexOf(markerEnd) + markerEnd.length;
        content =
            content.slice(0, start) +
            `${markerStart}\n${workspacesBlock}\n${markerEnd}` +
            content.slice(end);
    } else {
        // Inject before the closing `});` of defineConfig
        content = content.replace(
            /(\nexport default defineConfig\(\{)/,
            `\nexport default defineConfig({\n${markerStart}\n${workspacesBlock}\n${markerEnd}`,
        );
        // Replace the original `export default defineConfig({` if it already had content
        content = content.replace(
            /export default defineConfig\(\{\n {4}\/\/ SYNC-VERSIONS:START/,
            `export default defineConfig({\n    // SYNC-VERSIONS:START`,
        );
    }

    await writeOrPreview(sourceConfigPath, content);
}

// ── Step 6: Generate lib/source/index.tsx ─────────────────────────────────────

async function updateSourceIndex(latest: string, frozen: string[]): Promise<void> {
    let content = await readFile(sourceIndexPath, 'utf8');

    const allVersions = [latest, ...frozen].sort((a, b) => compareSemver(b, a));

    // Build import lines for workspace collections
    // fumadocs-mdx generates: collections/<workspace-name>/server
    const importLines = allVersions
        .map((v) => {
            const alias = `apiV${v.replace(/\./g, '_')}`;
            return `import * as ${alias} from 'collections/${v}/server';`;
        })
        .join('\n');

    const moduleMapEntries = allVersions
        .map((v) => {
            const alias = `apiV${v.replace(/\./g, '_')}`;
            return `    '${v}': ${alias},`;
        })
        .join('\n');

    const apiSourcesEntries = allVersions
        .map((v) => {
            return `    '${v}': loader({ baseUrl: '/api/${v}', i18n, source: versionModules['${v}'].docs.toFumadocsSource() }),`;
        })
        .join('\n');

    const markerStart = '// SYNC-VERSIONS:START';
    const markerEnd = '// SYNC-VERSIONS:END';

    const generatedBlock = `${markerStart}
${importLines}

type VersionModule = { docs: { toFumadocsSource: (opts?: object) => Parameters<typeof loader>[0]['source'] } };

const versionModules: Record<string, VersionModule> = {
${moduleMapEntries}
};

export const apiSources = {
${apiSourcesEntries}
} as const;
${markerEnd}`;

    if (content.includes(markerStart)) {
        const start = content.indexOf(markerStart);
        const end = content.indexOf(markerEnd) + markerEnd.length;
        content = content.slice(0, start) + generatedBlock + content.slice(end);
    } else {
        // Remove the old hardcoded apiSources block and replace
        content = content.replace(
            /\/\/ Old imports for apiDocs[\s\S]*?(?=\nexport const docsSource)/,
            '',
        );
        // Find the old apiSources export and replace
        content = content.replace(
            /export const apiSources = \{[\s\S]*?\} as const;/,
            generatedBlock,
        );
    }

    await writeOrPreview(sourceIndexPath, content);
}

// ── Helpers ───────────────────────────────────────────────────────────────────

async function writeOrPreview(filePath: string, content: string): Promise<void> {
    const rel = path.relative(docsRoot, filePath);
    if (DRY_RUN) {
        console.log(`\n[DRY-RUN] Would write: ${rel}`);
        console.log('─'.repeat(60));
        console.log(content.slice(0, 800) + (content.length > 800 ? '\n...(truncated)' : ''));
        console.log('─'.repeat(60));
    } else {
        await writeFile(filePath, content, 'utf8');
        console.log(`  ✓ Written: ${rel}`);
    }
}

// ── Main ──────────────────────────────────────────────────────────────────────

async function main() {
    console.log(`\n${DRY_RUN ? '🔍 DRY-RUN: ' : ''}sync-versions — scanning versions...\n`);

    const frozen = await parseFrozenVersions();
    const latest = await detectLatestVersion(new Set(frozen));

    if (!latest) {
        console.error('❌ No latest version found in content/api/. Aborting.');
        process.exit(1);
    }

    const allVersions = [latest, ...frozen].sort((a, b) => compareSemver(b, a));

    console.log(`  Latest  : ${latest}`);
    console.log(`  Frozen  : ${frozen.join(', ') || '(none)'}`);
    console.log(`  All     : ${allVersions.join(' > ')}\n`);

    // Ensure source.config.ts in each version dir
    for (const v of allVersions) {
        await ensureVersionConfig(v);
    }

    // Generate lib/versions.ts
    const versionsContent = generateVersionsTs(latest, frozen);
    await writeOrPreview(versionsPath, versionsContent);

    // Update source.config.ts
    await updateSourceConfig(allVersions);

    // Update lib/source/index.tsx
    await updateSourceIndex(latest, frozen);

    console.log(`\n${DRY_RUN ? '🔍 Dry-run complete.' : '✅ sync-versions complete.'}\n`);
}

main().catch((err) => {
    console.error('sync-versions failed:', err);
    process.exit(1);
});
