# Title:   JPT.UpdateCheckboxWatchSelected()
# Desc:    Select (Checked)/Deselect (Unchecked) entities by specifying their ID and their type
# Version: 5.0.1
# Docs:    /docs/cli/5.0.1/psj-utility/PSJ-Utility_UpdateCheckboxWatchSelected
# ---
Geometry.Part.Cube()
Geometry.Part.Cube(dlOrigin=[0.01, 0.0, 0.0],
                   strName="Cube_2",
                   iPartColor=6409934)
Geometry.Part.Cube(dlOrigin=[0.02, 0.0, 0.0],
                   strName="Cube_3",
                   iPartColor=13259210)
Geometry.Part.Cube(dlOrigin=[0.03, 0.0, 0.0],
                   strName="Cube_4",
                   iPartColor=7697908)
Geometry.Part.Cube(dlOrigin=[0.04, 0.0, 0.0],
                   strName="Cube_5",
                   iPartColor=7463537)
Geometry.Part.Cube(dlOrigin=[0.05, 0.0, 0.0],
                   strName="Cube_6",
                   iPartColor=7434735)
Geometry.Part.Cube(dlOrigin=[0.06, 0.0, 0.0],
                   strName="Cube_7",
                   iPartColor=14903267)
Geometry.Part.Cube(dlOrigin=[0.07, 0.0, 0.0],
                   strName="Cube_8",
                   iPartColor=15658599)
JPT.ViewFitToModel()

Tools.Renumber(listRenumberItem=[RENUMBER_ITEM(crTarget=Part(1),
                                               iBeginID=1,
                                               iCount=488,
                                               ilOffset=[10000, 100, 1],
                                               dlCoordTolerance=[0.1, 0.1, 0.1],
                                               bEnable=True),
                                 RENUMBER_ITEM(crTarget=Part(2),
                                               iBeginID=489,
                                               iCount=488,
                                               ilOffset=[10000, 100, 1],
                                               dlCoordTolerance=[0.1, 0.1, 0.1],
                                               bEnable=True),
                                 RENUMBER_ITEM(crTarget=Part(3),
                                               iBeginID=977,
                                               iCount=488,
                                               ilOffset=[10000, 100, 1],
                                               dlCoordTolerance=[0.1, 0.1, 0.1],
                                               bEnable=True),
                                 RENUMBER_ITEM(crTarget=Part(4),
                                               iBeginID=1465,
                                               iCount=488,
                                               ilOffset=[10000, 100, 1],
                                               dlCoordTolerance=[0.1, 0.1, 0.1],
                                               bEnable=True),
                                 RENUMBER_ITEM(crTarget=Part(5),
                                               iBeginID=1953,
                                               iCount=488,
                                               ilOffset=[10000, 100, 1],
                                               dlCoordTolerance=[0.1, 0.1, 0.1],
                                               bEnable=True),
                                 RENUMBER_ITEM(crTarget=Part(6),
                                               iBeginID=2441,
                                               iCount=488,
                                               ilOffset=[10000, 100, 1],
                                               dlCoordTolerance=[0.1, 0.1, 0.1],
                                               bEnable=True),
                                 RENUMBER_ITEM(crTarget=Part(7),
                                               iBeginID=2929,
                                               iCount=488,
                                               ilOffset=[10000, 100, 1],
                                               dlCoordTolerance=[0.1, 0.1, 0.1],
                                               bEnable=True),
                                 RENUMBER_ITEM(crTarget=Part(8),
                                               iBeginID=3417,
                                               iCount=488,
                                               ilOffset=[10000, 100, 1],
                                               dlCoordTolerance=[0.1, 0.1, 0.1],
                                               bEnable=True)])
Tools.Renumber(listRenumberItem=[RENUMBER_ITEM(crTarget=Part(1),
                                               iBeginID=1,
                                               iTargetType=2,
                                               iCount=972,
                                               ilOffset=[10000, 100, 1],
                                               dlCoordTolerance=[0.1, 0.1, 0.1],
                                               bEnable=True),
                                 RENUMBER_ITEM(crTarget=Part(2),
                                               iBeginID=973,
                                               iTargetType=2,
                                               iCount=972,
                                               ilOffset=[10000, 100, 1],
                                               dlCoordTolerance=[0.1, 0.1, 0.1],
                                               bEnable=True),
                                 RENUMBER_ITEM(crTarget=Part(3),
                                               iBeginID=1945, iTargetType=2,
                                               iCount=972,
                                               ilOffset=[10000, 100, 1],
                                               dlCoordTolerance=[0.1, 0.1, 0.1],
                                               bEnable=True),
                                 RENUMBER_ITEM(crTarget=Part(4),
                                               iBeginID=2917,
                                               iTargetType=2,
                                               iCount=972,
                                               ilOffset=[10000, 100, 1],
                                               dlCoordTolerance=[0.1, 0.1, 0.1],
                                               bEnable=True),
                                 RENUMBER_ITEM(crTarget=Part(5),
                                               iBeginID=3889,
                                               iTargetType=2,
                                               iCount=972,
                                               ilOffset=[10000, 100, 1],
                                               dlCoordTolerance=[0.1, 0.1, 0.1],
                                               bEnable=True),
                                 RENUMBER_ITEM(crTarget=Part(6),
                                               iBeginID=4861,
                                               iTargetType=2,
                                               iCount=972,
                                               ilOffset=[10000, 100, 1],
                                               dlCoordTolerance=[0.1, 0.1, 0.1],
                                               bEnable=True),
                                 RENUMBER_ITEM(crTarget=Part(7),
                                               iBeginID=5833,
                                               iTargetType=2,
                                               iCount=972,
                                               ilOffset=[10000, 100, 1],
                                               dlCoordTolerance=[0.1, 0.1, 0.1],
                                               bEnable=True),
                                 RENUMBER_ITEM(crTarget=Part(8),
                                               iBeginID=6805,
                                               iTargetType=2,
                                               iCount=972,
                                               ilOffset=[10000, 100, 1],
                                               dlCoordTolerance=[0.1, 0.1, 0.1],
                                               bEnable=True)],
               bAssignProp=False)

Home.Find(strSearch="1 2 3 4 5",
          strSelectedType="Node")
Home.Find(strSearch="1 2 3 4 5",
          strSelectedType="2D Element")

JPT.UpdateCheckboxWatchSelected(JPT.DItemType.NODE,  # [hl:start]
                                [1, 2, 3],
                                JPT.BoolType.FALSE_VAL)
JPT.UpdateCheckboxWatchSelected(JPT.DItemType.ELEM,
                                [1, 2, 3],
                                JPT.BoolType.FALSE_VAL)  # [hl:end]
